{% set name = "python-terraform" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beelit94/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 77bad01dc61a0b3e5aede028d0e679e00c290c3f9d3178d03f426ad019c76248

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - python_terraform

about:
  home: https://github.com/beelit94/python-terraform
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This is a python module provide a wrapper of terraform command line tool
  dev_url: https://github.com/beelit94/python-terraform

extra:
  recipe-maintainers:
    - agcopenhaver
    - oblute
    - rluria14
