travis:
  secure:
    BINSTAR_TOKEN: yGRDkDahP0EVLcHzGIqQpWDfu0CWjPkJQiV5nbuvfSnseAVyEG4Jn63pPyH9rOygcEvNLDdgMwEkCFDknwmkF3N/Nh8/OCm8KiO9yXbWkPqpXyElk0P2SmS5NuEB7tlOuvHVcxiY8MGKCZ63r+MZbXaAx2vjCMvPD6RpP3FaAUJO/SZzYKMCIOdlx2j7rpLgC+UkR0C7BLFBEEp4GSjG6v/Qh6q1JEa1SdR7SCkDrbbgVqKkpEZoqUk8+vMd+rZqykEz4I4IdcvE2NxNAVnrJ29UlXsKt6iaQovCq6uwrRccHnEeC3G+aw+Q3TlxlV4d9+eU3lDKEM02W8BKuSIUwDY8BKBE+l5Qz0Jq2v+/hl0YAEgTUehmgFquygCzF/4P2SF2GSdJMrl25jCMEqId6L8EUyfClOUDna4Tmrpwg4mXgTkfBufaVB33T3Dyz6pn8D6qyxYc1ByXBdQkHgF8yind54kmXpWhtMa5FML6LB8fdO77H0nIGWbp3HngLxtr4hzEKx45IdkhXnXMdjxyszypM/rp388To9CbzShDJcKnagBwvniwcXY7T9VMQW81e0j8EZ77eC0DUdJpXLNUfE2NmDv3e+DM4DXrQzCeXu19eJScPGe+1BUzvm1lFB1Sl5RE4idPSrK+iHfjZkCLgOCimF+GvuR6iEfZbSb5ah4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
